name: SPax
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pip:
    - jax -f https://storage.googleapis.com/jax-releases/jax_releases.html
    - jaxlib==0.1.65+cuda110 -f https://storage.googleapis.com/jax-releases/jax_releases.html