name: SPax_gpu
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - pip:
    - jax
    - https://storage.googleapis.com/jax-releases/cuda110/jaxlib-0.1.65+cuda110-cp38-none-manylinux2010_x86_64.whl
